### ISSUE TITLE
Go build fails with `cannot use X (type *int64) as type *int in field value`

### ISSUE THREAD

**Issue by eur0pa** [michenriksen/gitrob#129]
Hi there,
just trying a regular build and it's failing:

```
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77

❯ go version
go version go1.10.3 darwin/amd64

❯ go get -v github.com/michenriksen/gitrob
github.com/michenriksen/gitrob (download)
github.com/michenriksen/gitrob/core
# github.com/michenriksen/gitrob/core
go/src/github.com/michenriksen/gitrob/core/github.go:43:7: cannot use user.ID (type *int64) as type *int in field value
go/src/github.com/michenriksen/gitrob/core/github.go:73:13: cannot use repo.ID (type *int64) as type *int in field value
go/src/github.com/michenriksen/gitrob/core/github.go:105:75: cannot use member.ID (type *int64) as type *int in field value
```

**Comment by michenriksen** [comment]
Thanks for reporting! Unfortunately I can't reproduce this issue on my Mac. Does the precompiled binary work for you?

**Comment by eur0pa** [comment]
Yup, the pre-compiled version works out of the box. Very weird I can't seem to compile it with a simple `go get`, it will always fail with the same error. Same go version as mine?

**Comment by michenriksen** [comment]
Yes, I use 1.10.3 too. Could you try giving the go get command the `-u` flag too? Maybe it's using an old version of the Github package.

**Comment by eur0pa** [comment]
No cigar. Dump follows:


```
~
❯ rm -rf ~/go/{src,pkg}

❯ go get -u -v github.com/michenriksen/gitrob
Last login: Sat Jun  9 17:28:25 on ttys002

~
❯ go get -u -v github.com/michenriksen/gitrob
github.com/michenriksen/gitrob (download)
github.com/elazarl/go-bindata-assetfs (download)
github.com/fatih/color (download)
github.com/gin-contrib/secure (download)
github.com/gin-gonic/gin (download)
github.com/gin-contrib/sse (download)
github.com/golang/protobuf (download)
github.com/ugorji/go (download)
Fetching https://gopkg.in/go-playground/validator.v8?go-get=1
Parsing meta tags from https://gopkg.in/go-playground/validator.v8?go-get=1 (status code 200)
get "gopkg.in/go-playground/validator.v8": found meta tag get.metaImport{Prefix:"gopkg.in/go-playground/validator.v8", VCS:"git", RepoRoot:"https://gopkg.in/go-playground/validator.v8"} at https://gopkg.in/go-playground/validator.v8?go-get=1
gopkg.in/go-playground/validator.v8 (download)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/mattn/go-isatty (download)
github.com/gin-contrib/static (download)
github.com/google/go-github (download)
github.com/google/go-querystring (download)
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2?go-get=1
golang.org/x/oauth2 (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://golang.org/x/oauth2/internal?go-get=1
Parsing meta tags from https://golang.org/x/oauth2/internal?go-get=1 (status code 200)
get "golang.org/x/oauth2/internal": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2/internal?go-get=1
get "golang.org/x/oauth2/internal": verifying non-authoritative meta tag
Fetching https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
Fetching https://golang.org/x/net/context/ctxhttp?go-get=1
Parsing meta tags from https://golang.org/x/net/context/ctxhttp?go-get=1 (status code 200)
get "golang.org/x/net/context/ctxhttp": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context/ctxhttp?go-get=1
get "golang.org/x/net/context/ctxhttp": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4?go-get=1
gopkg.in/src-d/go-git.v4 (download)
github.com/sergi/go-diff (download)
Fetching https://gopkg.in/src-d/go-billy.v4?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-billy.v4?go-get=1 (status code 200)
get "gopkg.in/src-d/go-billy.v4": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-billy.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-billy.v4"} at https://gopkg.in/src-d/go-billy.v4?go-get=1
gopkg.in/src-d/go-billy.v4 (download)
Fetching https://gopkg.in/src-d/go-billy.v4/osfs?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-billy.v4/osfs?go-get=1 (status code 200)
get "gopkg.in/src-d/go-billy.v4/osfs": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-billy.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-billy.v4"} at https://gopkg.in/src-d/go-billy.v4/osfs?go-get=1
get "gopkg.in/src-d/go-billy.v4/osfs": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-billy.v4?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-billy.v4?go-get=1 (status code 200)
Fetching https://gopkg.in/src-d/go-billy.v4/helper/chroot?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-billy.v4/helper/chroot?go-get=1 (status code 200)
get "gopkg.in/src-d/go-billy.v4/helper/chroot": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-billy.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-billy.v4"} at https://gopkg.in/src-d/go-billy.v4/helper/chroot?go-get=1
get "gopkg.in/src-d/go-billy.v4/helper/chroot": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-billy.v4/helper/polyfill?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-billy.v4/helper/polyfill?go-get=1 (status code 200)
get "gopkg.in/src-d/go-billy.v4/helper/polyfill": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-billy.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-billy.v4"} at https://gopkg.in/src-d/go-billy.v4/helper/polyfill?go-get=1
get "gopkg.in/src-d/go-billy.v4/helper/polyfill": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-billy.v4/util?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-billy.v4/util?go-get=1 (status code 200)
get "gopkg.in/src-d/go-billy.v4/util": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-billy.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-billy.v4"} at https://gopkg.in/src-d/go-billy.v4/util?go-get=1
get "gopkg.in/src-d/go-billy.v4/util": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/config?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/config?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/config": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/config?go-get=1
get "gopkg.in/src-d/go-git.v4/config": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4?go-get=1 (status code 200)
Fetching https://gopkg.in/src-d/go-git.v4/plumbing?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/config?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/config?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/config": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/config?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/config": verifying non-authoritative meta tag
github.com/src-d/gcfg (download)
Fetching https://gopkg.in/warnings.v0?go-get=1
Parsing meta tags from https://gopkg.in/warnings.v0?go-get=1 (status code 200)
get "gopkg.in/warnings.v0": found meta tag get.metaImport{Prefix:"gopkg.in/warnings.v0", VCS:"git", RepoRoot:"https://gopkg.in/warnings.v0"} at https://gopkg.in/warnings.v0?go-get=1
gopkg.in/warnings.v0 (download)
Fetching https://gopkg.in/src-d/go-git.v4/internal/revision?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/internal/revision?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/internal/revision": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/internal/revision?go-get=1
get "gopkg.in/src-d/go-git.v4/internal/revision": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/filemode?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/filemode?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/filemode": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/filemode?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/filemode": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/gitignore?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/gitignore?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/gitignore": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/gitignore?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/gitignore": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/ioutil?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/ioutil?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/ioutil": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/ioutil?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/ioutil": verifying non-authoritative meta tag
github.com/jbenet/go-context (download)
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/index?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/index?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/index": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/index?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/index": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/binary?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/binary?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/binary": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/binary?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/binary": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/packfile?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/packfile?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/packfile": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/packfile?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/packfile": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/cache?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/cache?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/cache": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/cache?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/cache": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/idxfile?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/idxfile?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/idxfile": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/idxfile?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/idxfile": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/storer?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/storer?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/storer": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/storer?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/storer": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/object?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/object?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/object": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/object?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/object": verifying non-authoritative meta tag
github.com/emirpasic/gods (download)
Fetching https://golang.org/x/crypto/openpgp?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp?go-get=1
get "golang.org/x/crypto/openpgp": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/crypto/openpgp/armor?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/armor?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp/armor": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp/armor?go-get=1
get "golang.org/x/crypto/openpgp/armor": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/openpgp/errors?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/errors?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp/errors": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp/errors?go-get=1
get "golang.org/x/crypto/openpgp/errors": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/openpgp/packet?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/packet?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp/packet": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp/packet?go-get=1
get "golang.org/x/crypto/openpgp/packet": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/cast5?go-get=1
Parsing meta tags from https://golang.org/x/crypto/cast5?go-get=1 (status code 200)
get "golang.org/x/crypto/cast5": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/cast5?go-get=1
get "golang.org/x/crypto/cast5": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/openpgp/elgamal?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/elgamal?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp/elgamal": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp/elgamal?go-get=1
get "golang.org/x/crypto/openpgp/elgamal": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/openpgp/s2k?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/s2k?go-get=1 (status code 200)
get "golang.org/x/crypto/openpgp/s2k": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/openpgp/s2k?go-get=1
get "golang.org/x/crypto/openpgp/s2k": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/diff?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/diff?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/diff": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/diff?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/diff": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/diff?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/diff?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/diff": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/diff?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/diff": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/merkletrie?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/merkletrie?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/merkletrie": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/merkletrie?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/merkletrie": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/merkletrie/noder?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/merkletrie/noder?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/noder": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/merkletrie/noder?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/noder": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/norm?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/norm?go-get=1 (status code 200)
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/protocol/packp": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/protocol/packp": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/pktline?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/pktline?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/pktline": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/pktline?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/pktline": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/capability?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/capability?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/capability": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/capability?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/capability": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/storage/memory?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/storage/memory?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/storage/memory": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/storage/memory?go-get=1
get "gopkg.in/src-d/go-git.v4/storage/memory": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/storage?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/storage?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/storage": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/storage?go-get=1
get "gopkg.in/src-d/go-git.v4/storage": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/revlist?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/revlist?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/revlist": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/revlist?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/revlist": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/client?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/client?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/client": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/client?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/client": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/file?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/file?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/file": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/file?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/file": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/server?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/server?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/server": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/server?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/server": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/storage/filesystem?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/storage/filesystem?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/storage/filesystem": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/storage/filesystem?go-get=1
get "gopkg.in/src-d/go-git.v4/storage/filesystem": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/format/objfile?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/format/objfile?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/format/objfile": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/format/objfile?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/format/objfile": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit?go-get=1
get "gopkg.in/src-d/go-git.v4/storage/filesystem/dotgit": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/git?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/git?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/git": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/git?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/git": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/http?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/http?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/http": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/http?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/http": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/plumbing/transport/ssh?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/plumbing/transport/ssh?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/plumbing/transport/ssh?go-get=1
get "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh": verifying non-authoritative meta tag
github.com/kevinburke/ssh_config (download)
github.com/pelletier/go-buffruneio (download)
github.com/mitchellh/go-homedir (download)
github.com/xanzy/ssh-agent (download)
Fetching https://golang.org/x/crypto/ssh/agent?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh/agent?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/agent": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh/agent?go-get=1
get "golang.org/x/crypto/ssh/agent": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ed25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ed25519?go-get=1 (status code 200)
get "golang.org/x/crypto/ed25519": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ed25519?go-get=1
get "golang.org/x/crypto/ed25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1 (status code 200)
get "golang.org/x/crypto/ed25519/internal/edwards25519": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ed25519/internal/edwards25519?go-get=1
get "golang.org/x/crypto/ed25519/internal/edwards25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ssh?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh?go-get=1
get "golang.org/x/crypto/ssh": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/curve25519?go-get=1
Parsing meta tags from https://golang.org/x/crypto/curve25519?go-get=1 (status code 200)
get "golang.org/x/crypto/curve25519": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/curve25519?go-get=1
get "golang.org/x/crypto/curve25519": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/internal/chacha20?go-get=1
Parsing meta tags from https://golang.org/x/crypto/internal/chacha20?go-get=1 (status code 200)
get "golang.org/x/crypto/internal/chacha20": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/internal/chacha20?go-get=1
get "golang.org/x/crypto/internal/chacha20": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/poly1305?go-get=1
Parsing meta tags from https://golang.org/x/crypto/poly1305?go-get=1 (status code 200)
get "golang.org/x/crypto/poly1305": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/poly1305?go-get=1
get "golang.org/x/crypto/poly1305": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto/ssh/knownhosts?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh/knownhosts?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/knownhosts": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh/knownhosts?go-get=1
get "golang.org/x/crypto/ssh/knownhosts": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/merkletrie/filesystem?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/merkletrie/filesystem?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/filesystem": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/merkletrie/filesystem?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/filesystem": verifying non-authoritative meta tag
Fetching https://gopkg.in/src-d/go-git.v4/utils/merkletrie/index?go-get=1
Parsing meta tags from https://gopkg.in/src-d/go-git.v4/utils/merkletrie/index?go-get=1 (status code 200)
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/index": found meta tag get.metaImport{Prefix:"gopkg.in/src-d/go-git.v4", VCS:"git", RepoRoot:"https://gopkg.in/src-d/go-git.v4"} at https://gopkg.in/src-d/go-git.v4/utils/merkletrie/index?go-get=1
get "gopkg.in/src-d/go-git.v4/utils/merkletrie/index": verifying non-authoritative meta tag
github.com/michenriksen/gitrob/core
# github.com/michenriksen/gitrob/core
go/src/github.com/michenriksen/gitrob/core/github.go:43:7: cannot use user.ID (type *int64) as type *int in field value
go/src/github.com/michenriksen/gitrob/core/github.go:73:13: cannot use repo.ID (type *int64) as type *int in field value
go/src/github.com/michenriksen/gitrob/core/github.go:105:75: cannot use member.ID (type *int64) as type *int in field value

~ 1m 2s
```

**Comment by jaikishantulswani** [comment]
Getting the same 

$ go get github.com/michenriksen/gitrob
# github.com/michenriksen/gitrob/core
github.com/michenriksen/gitrob/core/github.go:43:7: cannot use user.ID (type *int64) as type *int in field value
github.com/michenriksen/gitrob/core/github.go:73:13: cannot use repo.ID (type *int64) as type *int in field value
github.com/michenriksen/gitrob/core/github.go:105:75: cannot use member.ID (type *int64) as type *int in field value

**Comment by heidark** [comment]
Same here, changing `int` to `int64` allows me to build it.

The ID in User struct is a int64: https://github.com/google/go-github/blob/master/github/users.go#L22

The PR that changed ID's from int to int64 is here: https://github.com/google/go-github/pull/816

@michenriksen is your `google/go-github` up to date?

**Comment by michenriksen** [comment]
Hmm, yes, it's the latest version. :confused:

**Comment by michenriksen** [comment]
Oh, my bad. I was actually running with an older version of `go-github` I fixed the code to use `*int64` for ID fields now, so `go get` should work.

**Comment by jaikishantulswani** [comment]
Why I am still getting the same error

go get github.com/michenriksen/gitrob
# github.com/michenriksen/gitrob/core
go/src/github.com/michenriksen/gitrob/core/github.go:43:7: cannot use user.ID (type *int64) as type *int in field value
go/src/github.com/michenriksen/gitrob/core/github.go:73:13: cannot use repo.ID (type *int64) as type *int in field value
go/src/github.com/michenriksen/gitrob/core/github.go:105:75: cannot use member.ID (type *int64) as type *int in field value

**Comment by davidcreus** [comment]
Same error.

# github.com/michenriksen/gitrob/core
/home/davidcreus/bin/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:43:5: cannot use user.ID (type *int64) as type *int in field value
/home/davidcreus/bin/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:73:11: cannot use repo.ID (type *int64) as type *int in field value
/home/davidcreus/bin/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:105:73: cannot use member.ID (type *int64) as type *int in field value

**Comment by sentago** [comment]
Hey, i'm getting the below errors:

root@kali:~# go get github.com/michenriksen/gitrob
# runtime/internal/atomic
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:13:6: Load redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:16:24
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:19:6: Loadp redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:22:32
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:25:6: Load64 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:28:26
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:31:6: LoadAcq redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:34:27
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: Xadd redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:39:37
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:39:6: Xadd64 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:42:39
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:42:6: Xadduintptr redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:45:47
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:45:6: Xchg redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:48:36
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:48:6: Xchg64 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:51:38
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:51:6: Xchguintptr redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:54:45
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:51:6: too many errors

**Comment by pankajninjasec** [comment]
# github.com/michenriksen/gitrob/core
go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal

I am getting this error .

**Comment by dirtcrosser** [comment]
> # github.com/michenriksen/gitrob/core
> go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
> 
> I am getting this error .

I got the same error. how to fix this issue?

**Comment by rameshkumar-rk** [comment]
github.com/michenriksen/gitrob/core
/usr/local/go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal

Errors Errors Errors Errors

**Comment by AirSmasher** [comment]
github.com/michenriksen/gitrob/core
# github.com/michenriksen/gitrob/core
go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
I have the same error too.
please , help

**Comment by nirajdhalani** [comment]
go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
i also get same error how to fix this please replay

**Comment by BrunoJu** [comment]
I got same issue exactly.
`go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal`
Can anyone fix that?  It's too hard to install this gitrob repository, almost drive me mad.

**Comment by Tcarters** [comment]
@michenriksen  Plz come to give us a better solution this problem 

github.com/michenriksen/gitrob/core
../../../go/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:43:5: cannot use user.ID (type *int64) as type *int in field value
../../../go/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:73:11: cannot use repo.ID (type *int64) as type *int in field value
../../../go/pkg/mod/github.com/michenriksen/gitrob@v2.0.0-beta+incompatible/core/github.go:105:73: cannot use member.ID (type *int64) as type *int in field value


Despite the fact that i changed all the **int** in ur code by **int64**, i still get the same blem 
Any suggestion

**Comment by dhruv-kandpal** [comment]
/root/go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
Same error! :(

**Comment by preethamarun00** [comment]
look  at your grub file or reinstall grub menu 
 second nope is just check your cmd commands
