### ISSUE TITLE
Failed to access Github Enterprise with last version.

### ISSUE THREAD

**Issue by tinsjourney** [michenriksen/gitrob#52]
Hi,

As we have a Github Enterprise instance where I work, I gave a try on the new version.
But doesn't seem to work.

Here's the ouput of my analyze command.

```
# gitrob analyze MyOrganization  --site=https://github.enterprise.local --endpoint=https://github.enterprise.local/api/v3 --access-tokens="249cd50a190035d644b3e8e1fa36a8dbaa86eb67"
     _ _           _
 ___|_| |_ ___ ___| |_
| . | |  _|  _| . | . |
|_  |_|_| |_| |___|___|
|___| By @michenriksen

[*] Starting Gitrob version 1.0.0 at 2016-03-15 15:38 UTC
[*] Loading configuration... done
[*] Preparing database... done
[*] Loading signatures... done
/var/lib/gems/2.1.0/gems/gitrob-1.0.0/lib/gitrob/cli/commands/analyze/gathering.rb:60:in `github_access_tokens': undefined method `gsub' for ["249cd50a190035d644b3e8e1fa36a8dbaa86eb67"]:Array (NoMethodError)
        from /var/lib/gems/2.1.0/gems/gitrob-1.0.0/lib/gitrob/cli/commands/analyze.rb:34:in `create_database_assessment'
        from /var/lib/gems/2.1.0/gems/gitrob-1.0.0/lib/gitrob/cli/commands/analyze.rb:16:in `initialize'
        from /var/lib/gems/2.1.0/gems/gitrob-1.0.0/lib/gitrob/cli/command.rb:7:in `new'
        from /var/lib/gems/2.1.0/gems/gitrob-1.0.0/lib/gitrob/cli/command.rb:7:in `start'
        from /var/lib/gems/2.1.0/gems/gitrob-1.0.0/lib/gitrob/cli.rb:84:in `analyze'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.1.0/gems/gitrob-1.0.0/exe/gitrob:5:in `<top (required)>'
        from /usr/local/bin/gitrob:22:in `load'
        from /usr/local/bin/gitrob:22:in `<main>'```

**Gitrob version:** 1.0.0
**OS and version:** Debian Jessie
**Ruby version:** 2.1.5p273
**PostgreSQL version:** 9.4.6

**Comment by jstoneky** [comment]
Move your access token into the gitrobrc file as a work around

**Comment by tinsjourney** [comment]
thanks @jstoneky I confim I don't have the same issue now.`
Now It's telling me that even with the '--no-verify-ssl' option it failed verifying the certificate.

```
# gitrob analyze MyOrganization --site=https://github.terprise.local  --endpoint=https://githubenterprise.local/api/v3 --no-verify-ssl
     _ _           _
 ___|_| |_ ___ ___| |_
| . | |  _|  _| . | . |
|_  |_|_| |_| |___|___|
|___| By @michenriksen

[*] Starting Gitrob version 1.0.0 at 2016-03-17 11:08 UTC
[*] Loading configuration... done
[*] Preparing database... done
[*] Loading signatures... done
[*] Gathering targets... failed
[!] Faraday::SSLError: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed
[!] No users or organizations found; exiting
```

**Comment by michenriksen** [comment]
Hi @tinsjourney, thanks for reporting. The problem with access token from the command-line option is a pretty easy fix that I will look into over the weekend. The SSL problem might be a bug in the `github_api` Gem, but I will look into that as well!

**Comment by michenriksen** [comment]
Hi @tinsjourney, I have fixed both the issue with not being able to set access tokens through the `--access-tokens` command option and the problem with `--verify-ssl` command option. The fixes are currently only in the `master` branch and hasn't been released yet before the fixes are confirmed to work.

Would you mind trying out the latest code in `master` by doing the following:

    $ git clone git@github.com:michenriksen/gitrob.git
    $ cd gitrob
    $ bundle install

And then trying again with the latest code with:

    $ bundle exec gitrob analyze MyOrganization --site=https://github.terprise.local  --endpoint=https://githubenterprise.local/api/v3 --no-verify-ssl

Thanks a lot for helping out!

**Comment by tinsjourney** [comment]
Hi @michenriksen !

I confirm the fix for the --access-tokens, but the --no-verify-ssl still doesn't work. I have the same error message as before (ie : [!] Faraday::SSLError: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed)
I'm not used to ruby, so I don't know how to add more verbosity in the script to give you more logs.
So feel free to tell me what I can do to give you more information on this issue.

**Comment by michenriksen** [comment]
Sorry, I'm an idiot. I pushed a fix to my fix now. Could you try again after doing a `git pull`?

Thanks again!

**Comment by tinsjourney** [comment]
I confirm I don't have the ssl issue anymore. :+1:  Thanks.

But now it says "it can't find my user or organizations"
Is there anyway to increase the verbosity to get more informations where it fails, I don't have many information with --debug

**Comment by michenriksen** [comment]
Right now, there is unfortunately only the `--debug` option. I will look into a way to make the `github_api` gem output the API endpoints it requests. 

Have you tried running the analyze command with a list of usernames?

**Comment by tinsjourney** [comment]
I tried with Organization Name, usernames, and list of usernames separated with comma.
But it doesn't find anything

**Comment by michenriksen** [comment]
Hi @tinsjourney, I've done some research and found out that request logging can be done easily because the `github_api` gem uses [faraday](https://github.com/lostisland/faraday) for HTTP communication.

If you run the command:

    $ DEBUG=true bundle exec gitrob analyze MyOrganization --site=https://github.terprise.local  --endpoint=https://githubenterprise.local/api/v3 --no-verify-ssl

You should see a bunch of debug output about which endpoints are being requested. Could you paste that in here, so we can see what's going on?

Sorry for this cumbersome process, I wish I had access to a GitHub Enterprise installation to make debugging easier. Thanks a lot helping out though, I really appreciate it!

**Comment by tinsjourney** [comment]
Hello @michenriksen ,

I don't know what I did last time, but now it's working. with both CLI or webserver. Maybe some module used by gitrob have been updated since.

I confirm everything is working now. We can close this issue

Thanks for your help and time, and fell free next time to contact me when you need to do more test on GitHub Enterprise.

**Comment by michenriksen** [comment]
I'm glad to hear that it's working for you! I'll close the ticket. I'll ping you if I need to test anything GitHub Enterprise.

**Comment by arunbalu123** [comment]
I got following error while running gitrob. Could you suggest me some help

[*] Starting Gitrob version 1.1.2 at 2017-09-08 12:42 IST
[*] Loading configuration... done
[*] Preparing database...SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:4:in `<class:Assessment>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:140:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:4:in `<class:GithubAccessToken>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:141:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:4:in `<class:Owner>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:142:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:4:in `<class:Repository>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:143:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:4:in `<class:Blob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:144:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:4:in `<class:Flag>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:145:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.1.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:4:in `<class:Comparison>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:3:in `<module:Models>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:146:in `load_models'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.1.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
 done
Gitrob commands:
  gitrob analyze TARGETS  # Analyze one or more organizations or users
  gitrob configure        # Start configuration wizard
  gitrob help [COMMAND]   # Describe available commands or one specific command
  gitrob server           # Start web server
